import 'package:appnavigation/Chess_Grid.dart';
import 'package:appnavigation/Ludo_Grid.dart';
import 'package:flutter/material.dart';

class MyHome extends StatelessWidget {
  const MyHome({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            SizedBox(
              height: 50,
            ),
            Container(
              height: 470,
              width: 470,
              decoration: BoxDecoration(
                  border: Border.all(color: Colors.black, width: 10)),
              child: Column(
                children: [
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(Colors.white),
                      LudoGrid3(Colors.white, Icon(Icons.arrow_downward)),
                      LudoGrid(Colors.white),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.yellow),
                      LudoGrid2(Colors.yellow),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.yellow),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.green),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid2(Colors.yellow),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.white),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.yellow),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.green),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.white),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.yellow),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.white),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.yellow),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(const Color.fromARGB(255, 168, 243, 171)),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.yellow),
                      LudoGrid(Colors.white),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                      LudoGrid(const Color.fromARGB(255, 247, 236, 141)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(Colors.white),
                      LudoGrid2(Colors.green),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid4(),
                      LudoGrid4(),
                      LudoGrid4(),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid2(Colors.blue),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid3(Colors.white, Icon(Icons.arrow_forward)),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid(Colors.green),
                      LudoGrid4(),
                      LudoGrid4(),
                      LudoGrid4(),
                      LudoGrid(Color.fromRGBO(3, 136, 245, 1)),
                      LudoGrid(Color.fromRGBO(3, 136, 245, 1)),
                      LudoGrid(Color.fromRGBO(3, 136, 245, 1)),
                      LudoGrid(Color.fromRGBO(3, 136, 245, 1)),
                      LudoGrid(Color.fromRGBO(3, 136, 245, 1)),
                      LudoGrid3(Colors.white, Icon(Icons.arrow_back)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid2(Colors.green),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid4(),
                      LudoGrid4(),
                      LudoGrid4(),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid2(Color.fromRGBO(3, 136, 245, 1)),
                      LudoGrid(Colors.white),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.white),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.red),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.white),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Colors.blue),
                      LudoGrid(Colors.blue),
                      LudoGrid(Colors.blue),
                      LudoGrid(Colors.blue),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.red),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.white),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Colors.blue),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.blue),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.red),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.red),
                      LudoGrid2(Colors.red),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Colors.blue),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.white),
                      LudoGrid(Colors.blue),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.red),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid2(Colors.red),
                      LudoGrid(Colors.red),
                      LudoGrid(Colors.white),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Colors.blue),
                      LudoGrid(Colors.blue),
                      LudoGrid(Colors.blue),
                      LudoGrid(Colors.blue),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                    ],
                  ),
                  Row(
                    children: [
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(const Color.fromARGB(255, 240, 177, 183)),
                      LudoGrid(Colors.white),
                      LudoGrid3(Colors.white, Icon(Icons.arrow_upward)),
                      LudoGrid(Colors.white),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                      LudoGrid(Color.fromARGB(255, 127, 193, 247)),
                    ],
                  ),
                ],
              ),
            ),
            SizedBox(
              height: 20,
            ),
            ElevatedButton(
                onPressed: () {
                  Navigator.push(context,
                      MaterialPageRoute(builder: (context) => Chess()));
                },
                child: Container(
                  height: 20,
                  width: 95,
                  child: Row(
                    children: [
                      Text("Chess Grid"),
                      Icon(Icons.radio_button_checked),
                    ],
                  ),
                ))
          ],
        ),
      ),
    );
  }
}
